name: Bump Helm Chart Version
description: Bump a Helm Chart Version Locally
branding:
  icon: hard-drive
  color: blue
inputs:
  app_version:
    description: to also bump app-version
    default: "true"
    required: false
  level:
    description: patch/minor/major
    required: true
  chart-path:
    description: the directory path to the specified chart (without / at the end)
    required: true
outputs:
  chart:
    description: "Chart name"    
    value: ${{ steps.version-tag.outputs.chart }}
  bumped_version:
    description: "Bumped Version"     
    value: ${{ steps.version-bump.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install PyBump
      run: |
        python3 -m pip install pybump
      shell: bash

    - name: Automated Version Bump
      id: version-bump
      run: |
        version=$(pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }})
        echo "::set-output name=bumped_version::$(echo $version)" 
        if [[ ${{ fromJSON(inputs.app_version) }} ]]
        then
          pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }} --app-version
        fi        
      shell: bash        

    - name: Output Name
      id: version-tag
      run: |
        echo "::set-output name=chart::$(basename ${{ inputs.chart-path }})"
      shell: bash
