name: Bump Helm Chart Version
description: Bump a Helm Chart Version Locally
branding:
  icon: hard-drive
  color: blue
inputs:
  app_version:
    description: to also bump app-version
    default: "false"
    required: false
  level:
    description: patch/minor/major
    required: true
  chart-path:
    description: the directory path to the specified chart (without / at the end)
    required: true
outputs:
  chart:
    description: "Chart name"
    value: ${{ steps.chart-name.outputs.chart }}
runs:
  using: "composite"
  steps:
    - name: Install PyBump
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip
        python3 -m pip install pybump
      shell: bash
    - name: Automated Version Bump
      id: version-bump
      run: |
        if [[ ${{ fromJSON(inputs.app_version) }} != "false" ]]
        then
          pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }} --app-version
        fi
        pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }}
      shell: bash
    - name: Output Name
      id: chart-name
      run: |
        echo "chart=$(basename ${{ inputs.chart-path }})" >> $GITHUB_ENV
      shell: bash
